[book]
title = "{{ cookiecutter.project_name }}"
author = "{{ cookiecutter.full_name }}"
description = "{{ cookiecutter.description }}"
language = "en"
multilingual = false
src = "docs-markdown"

[build]
build-dir = "docs"

[output.html]
additional-css = ["docs-markdown/css/styles.css"]
mathjax-support = true